### ISSUE TITLE
difficulty-2/implement simple form validation on login/signup pages

### ISSUE THREAD

**Issue by ranegray** [gschool-blue-ocean/admissions-hub-20#29]
might be blocked, requires auth full setup

utilize this resource: https://www.robinwieruch.de/react-form/#form-library-react-hook-form

**Comment by SaurabhS55** [comment]
Hey there,
I would like to contribute to this issue and was wondering if anyone is currently working on it. Please let me know if anyone working on this issue or if I can start working on this.

**Comment by jordan-carlson99** [comment]
removed for some other features, will be brought back for next sprint
