### ISSUE TITLE
build UI scaffold for student card on dashboard

### ISSUE THREAD

**Issue by ranegray** [gschool-blue-ocean/admissions-hub-20#5]
Layout fields with hard coded data to make sure we can embed the card next to the table on the dashboard.

![Image](https://github.com/gschool-blue-ocean/admissions-hub-20/assets/75066470/9c84637c-43dd-42aa-9bb1-763339869b15)

**Comment by DanielPurdy509** [comment]
Built out student card with mock data

<img width="202" alt="Blue_Ocean_Student_Card_Component" src="https://github.com/gschool-blue-ocean/admissions-hub-20/assets/125397922/5014b675-6b75-4cc5-80d5-095abf94d00b">
